FROM maven:3.6.3-jdk-8@sha256:ac624d39dd0b7bed827d4b0d1bbaeb457012e0cba0fb6c53ce34b00bed16ec08
LABEL maintainer="Shivakumar Ningappa <shivagowda@gmail.com>"


# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Java server app
RUN mvn clean package -DskipTests

# Expose default port for external communication
EXPOSE 8888

# Command to run the executable jar
CMD [ "java -jar target/jhttp-1.0-SNAPSHOT.jar" ]